#!/bin/bash

echo "[dropbear][INFO]: initialising dropbear keys..." > /dev/kmsg

if [[ ! -b /dev/disk/by-label/boot-storage ]]; then
    echo "[dropbear][ERROR] /dev/disk/by-label/boot not found!" > /dev/kmsg
    exit 1
fi

# Mount the boot partition (FCOS labels the boot partition as 'boot')
mkdir -p /mnt/boot-storage
if ! mount -L boot-storage /mnt/boot-storage; then
    echo "[dropbear][ERROR] failed to mount /mnt/boot-storage" > /dev/kmsg
    exit 1
fi

# Setup directories
mkdir -p /mnt/boot-storage/dropbear
mkdir -p /etc/dropbear
mkdir -p /root/.ssh

keys_path="/mnt/boot-storage/dropbear"

if [[ ! -f "$keys_path/dropbear_ecdsa_host_key" ]]; then
    echo "[dropbear][INFO]: generating new Dropbear ecdsa host key..." > /dev/kmsg
    dropbearkey -t ecdsa -f "$keys_path/dropbear_ecdsa_host_key"
else
    echo "[dropbear][INFO] found 'dropbear_ecdsa_host_key'!" > /dev/kmsg
fi

if [[ ! -f "$keys_path/dropbear_ed25519_host_key" ]]; then
    echo "[dropbear][INFO]: generating new Dropbear ED25519 host key..." > /dev/kmsg
    dropbearkey -t ed25519 -f "$keys_path/dropbear_ed25519_host_key"
else
    echo "[dropbear][INFO] found 'dropbear_ed25519_host_key'!" > /dev/kmsg
fi

if [[ ! -f "$keys_path/dropbear_rsa_host_key" ]]; then
    echo "[dropbear][INFO]: generating new Dropbear rsa host key..." > /dev/kmsg
    dropbearkey -t rsa -f "$keys_path/dropbear_rsa_host_key"
else
    echo "[dropbear][INFO] found 'dropbear_rsa_host_key'!" > /dev/kmsg
fi

echo "[dropbear][INFO] host key ECDSA: $(cat "$keys_path/dropbear_ecdsa_host_key.pub")" > /dev/kmsg
echo "[dropbear][INFO] host key Ed25519: $(cat "$keys_path/dropbear_ed25519_host_key.pub")" > /dev/kmsg
echo "[dropbear][INFO] host key RSA: $(cat "$keys_path/dropbear_rsa_host_key.pub")" > /dev/kmsg

cp "$keys_path/dropbear_ecdsa_host_key" /etc/dropbear/
cp "$keys_path/dropbear_ed25519_host_key" /etc/dropbear/
cp "$keys_path/dropbear_rsa_host_key" /etc/dropbear/

if [[ -f "$keys_path/authorized_keys" ]]; then
    echo "[dropbear][INFO] found 'authorized_keys'!" > /dev/kmsg

    cp "$keys_path/authorized_keys" /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
else
    echo "[dropbear][ERROR] missing '/boot/dropbear/authorized_keys'!" > /dev/kmsg
fi

umount /mnt/boot
